### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by ChristianBielak** [daun/laravel-mix-transpile-node-modules#1]
Hi,

i want to use your package but i'm running into to this Error when i start the production build.

TypeError: Cannot read property 'find' of undefined

**Comment by daun** [comment]
Could you post a dump of your final webpack config after Mix has done all its processing? The [laravel-mix-dump](https://www.npmjs.com/package/laravel-mix-dump) extension should do the trick.

**Comment by daun** [comment]
I'm mostly interested in the `babel-loader` options, but it won't hurt to have the whole output.

**Comment by daun** [comment]
I'll go ahead and close this for now. I'm happy to re-open and investigate if you publish your webpack config.
