### ISSUE TITLE
Support for laravel-mix:^6

### ISSUE THREAD

**Issue by marvinschroeder** [daun/laravel-mix-transpile-node-modules#4]
Do you plan to support laravel-mix:^6?

I hopefully landed here from https://github.com/JeffreyWay/laravel-mix/issues/2742 but just saw that this plugin supports version 4 of laravel-mix and that it has no effect in version 6.

**Comment by daun** [comment]
Sure, I'd love to support v6. All of my projects are still on v5 so there was no rush to take a closer look.

As far as I can tell, there aren't any changes to the plugin API, though. Is it working for you on v5 but stopped working on v6? Or is it a brand new install?

**Comment by marvinschroeder** [comment]
It's a brand new installation with v6. I did not tried it on v4 or v5.

**Comment by daun** [comment]
In that case, it might be a configuration issue as well. I'll do some tests to see if I get it working on v6.

**Comment by daun** [comment]
Found the issue. If you update to the [latest release](https://github.com/daun/laravel-mix-transpile-node-modules/releases/tag/v2.0.0), it should work with Mix v6.

**Comment by marvinschroeder** [comment]
Thanks! I think the mix.transpileNodeModules(); usage (without parameter) is broken. Only if i explicitly define true as a parameter, the webpack config changes.

**Comment by daun** [comment]
You're right. I pushed a fix at 2.0.1. Thanks for reporting!
